
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Apr 19 2024 11:01:48

// Verification Directory fv/mux 

module decrement_unsigned(A, CI, Z);
  input [3:0] A;
  input CI;
  output [3:0] Z;
  wire [3:0] A;
  wire CI;
  wire [3:0] Z;
  wire n_10, n_11, n_12, n_14, n_17, n_18, n_19;
  not g1 (n_10, A[0]);
  xor g11 (Z[0], A[0], CI);
  not g12 (n_17, n_11);
  xor g13 (Z[1], A[1], n_17);
  xor g14 (Z[2], A[2], n_14);
  not g15 (n_19, n_18);
  xor g16 (Z[3], A[3], n_19);
  nand g2 (n_11, n_10, CI);
  not g4 (n_12, A[2]);
  nor g6 (n_14, n_11, A[1]);
  nand g8 (n_18, n_12, n_14);
endmodule

module increment_unsigned(A, CI, Z);
  input [3:0] A;
  input CI;
  output [3:0] Z;
  wire [3:0] A;
  wire CI;
  wire [3:0] Z;
  wire n_10, n_11, n_12, n_15, n_16, n_17;
  nand g1 (n_10, A[0], CI);
  xor g10 (Z[1], A[1], n_15);
  xor g11 (Z[2], A[2], n_12);
  not g12 (n_17, n_16);
  xor g13 (Z[3], A[3], n_17);
  not g2 (n_11, A[1]);
  nor g3 (n_12, n_10, n_11);
  nand g5 (n_16, A[2], n_12);
  xor g8 (Z[0], A[0], CI);
  not g9 (n_15, n_10);
endmodule

module mux(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  decrement_unsigned dec_sub_53_17_2(.A (out), .CI (1'b1), .Z ({n_16,
       n_14, n_12, n_10}));
  increment_unsigned inc_add_56_17_1(.A (out), .CI (1'b1), .Z ({n_17,
       n_15, n_13, n_11}));
  not g1 (n_8, rst_n);
  not g6 (n_9, sel);
  CDN_flop \out_reg[0] (.clk (clk), .d (n_18), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[0]));
  CDN_flop \out_reg[1] (.clk (clk), .d (n_19), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[1]));
  CDN_flop \out_reg[2] (.clk (clk), .d (n_20), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[2]));
  CDN_flop \out_reg[3] (.clk (clk), .d (n_21), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[3]));
  CDN_bmux2 mux_out_52_17_g1(.sel0 (n_9), .data0 (n_17), .data1 (n_16),
       .z (n_21));
  CDN_bmux2 mux_out_52_17_g2(.sel0 (n_9), .data0 (n_15), .data1 (n_14),
       .z (n_20));
  CDN_bmux2 mux_out_52_17_g3(.sel0 (n_9), .data0 (n_13), .data1 (n_12),
       .z (n_19));
  CDN_bmux2 mux_out_52_17_g4(.sel0 (n_9), .data0 (n_11), .data1 (n_10),
       .z (n_18));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
