
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Apr 19 2024 11:01:49

// Verification Directory fv/mux 

module mux(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (n_12), .Q (out[3]));
  sky130_fd_sc_hd__xor2_1 g123(.A (n_8), .B (n_0), .X (n_12));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (n_11), .Q (out[2]));
  sky130_fd_sc_hd__o2bb2ai_1 g124(.A1_N (n_10), .A2_N (n_9), .B1
       (n_10), .B2 (n_9), .Y (n_11));
  sky130_fd_sc_hd__nor2_1 g126(.A (n_3), .B (n_9), .Y (n_8));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (n_7), .Q (out[1]));
  sky130_fd_sc_hd__o21ai_1 g127(.A1 (n_4), .A2 (sel), .B1 (n_5), .Y
       (n_9));
  sky130_fd_sc_hd__o2bb2ai_1 g128(.A1_N (n_6), .A2_N (sel), .B1 (n_6),
       .B2 (sel), .Y (n_7));
  sky130_fd_sc_hd__a21oi_1 g129(.A1 (sel), .A2 (n_4), .B1 (n_6), .Y
       (n_5));
  sky130_fd_sc_hd__o2bb2ai_1 g130(.A1_N (n_2), .A2_N (n_4), .B1 (n_2),
       .B2 (n_4), .Y (n_3));
  sky130_fd_sc_hd__o2bb2ai_1 g131(.A1_N (n_1), .A2_N (n_4), .B1 (n_1),
       .B2 (n_4), .Y (n_6));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (n_4), .Q (out[0]));
  sky130_fd_sc_hd__clkbuf_1 g135(.A (n_2), .X (n_10));
  sky130_fd_sc_hd__clkbuf_1 g133(.A (out[3]), .X (n_0));
  sky130_fd_sc_hd__clkbuf_1 g136(.A (out[2]), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g134(.A (out[1]), .X (n_1));
  sky130_fd_sc_hd__inv_2 g137(.A (out[0]), .Y (n_4));
endmodule

