
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Apr 19 2024 11:01:49

// Verification Directory fv/mux 

module mux(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire n_3, n_4, n_8, n_12, n_20, n_21, n_22, n_23;
  wire n_24, n_31;
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (n_12), .Q (out[3]));
  sky130_fd_sc_hd__xor2_1 g123(.A (n_8), .B (out[3]), .X (n_12));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (n_20), .Q (out[2]));
  sky130_fd_sc_hd__nor2_1 g126(.A (n_3), .B (n_22), .Y (n_8));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (n_23), .Q (out[1]));
  sky130_fd_sc_hd__o2bb2ai_1 g130(.A1_N (out[2]), .A2_N (n_4), .B1
       (out[2]), .B2 (n_4), .Y (n_3));
  sky130_fd_sc_hd__xnor2_1 g2(.A (out[2]), .B (n_22), .Y (n_20));
  sky130_fd_sc_hd__nand2b_1 g142(.A_N (n_24), .B (n_21), .Y (n_22));
  sky130_fd_sc_hd__xor2_1 g3(.A (n_4), .B (n_31), .X (n_21));
  sky130_fd_sc_hd__xnor2_1 g143(.A (n_24), .B (n_31), .Y (n_23));
  sky130_fd_sc_hd__xnor2_1 g144(.A (out[1]), .B (n_4), .Y (n_24));
  sky130_fd_sc_hd__buf_1 drc_buf_sp152(.A (sel), .X (n_31));
  sky130_fd_sc_hd__dfrbp_1 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (n_4), .Q (out[0]), .Q_N (n_4));
endmodule

