
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Apr 19 2024 11:01:48

// Verification Directory fv/mux 

module sub_unsigned(A, B, Z);
  input [3:0] A;
  input B;
  output [3:0] Z;
  wire [3:0] A;
  wire B;
  wire [3:0] Z;
  wire n_18, n_21, n_24, n_26, n_27, n_28, n_34, n_36;
  wire n_43, n_45;
  not g5 (n_18, B);
  xor g7 (n_45, A[0], n_18);
  nand g10 (n_24, n_21, B);
  nand g19 (n_34, n_26, n_27);
  nand g26 (n_43, n_28, n_36);
  xnor g30 (Z[1], n_24, A[1]);
  xnor g32 (Z[2], n_34, A[2]);
  xnor g35 (Z[3], n_43, A[3]);
  not g37 (n_28, A[2]);
  not g39 (n_26, A[1]);
  not g40 (n_21, A[0]);
  not g41 (Z[0], n_45);
  not g42 (n_27, n_24);
  not g43 (n_36, n_34);
endmodule

module add_unsigned(A, B, Z);
  input [3:0] A;
  input B;
  output [3:0] Z;
  wire [3:0] A;
  wire B;
  wire [3:0] Z;
  wire n_11, n_18, n_21, n_28, n_30, n_34, n_35, n_37;
  wire n_38;
  xor g1 (Z[0], A[0], B);
  nand g2 (n_11, A[0], B);
  nand g13 (n_21, n_18, A[1]);
  nand g20 (n_30, n_28, A[2]);
  xnor g25 (Z[1], n_18, n_34);
  xnor g27 (Z[2], n_28, n_35);
  xnor g30 (Z[3], n_37, n_38);
  not g35 (n_18, n_11);
  not g36 (n_34, A[1]);
  not g37 (n_35, A[2]);
  not g38 (n_38, A[3]);
  not g39 (n_28, n_21);
  not g40 (n_37, n_30);
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [3:0] in_0, in_1;
  output [3:0] z;
  wire ctl;
  wire [3:0] in_0, in_1;
  wire [3:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module mux(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_8, n_9,
       n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21;
  sub_unsigned sub_53_17(.A (out), .B (1'b1), .Z ({n_16, n_14, n_12,
       n_10}));
  add_unsigned add_56_17(.A (out), .B (1'b1), .Z ({n_17, n_15, n_13,
       n_11}));
  bmux mux_out_52_17(.ctl (n_9), .in_0 ({n_17, n_15, n_13, n_11}),
       .in_1 ({n_16, n_14, n_12, n_10}), .z ({n_21, n_20, n_19, n_18}));
  bmux mux_out_48_10(.ctl (n_8), .in_0 ({n_21, n_20, n_19, n_18}),
       .in_1 (4'b0000), .z ({UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED}));
  not g1 (n_8, rst_n);
  CDN_flop \out_reg[0] (.clk (clk), .d (n_18), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[0]));
  CDN_flop \out_reg[1] (.clk (clk), .d (n_19), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[1]));
  CDN_flop \out_reg[2] (.clk (clk), .d (n_20), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[2]));
  CDN_flop \out_reg[3] (.clk (clk), .d (n_21), .sena (1'b1), .aclr
       (n_8), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (out[3]));
  not g6 (n_9, sel);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
